version: 2
project_name: kubectl-nsenter
builds:
  - main: ./cmd/kubectl-nsenter
    binary: kubectl-nsenter-{{.Os}}-{{.Arch}}
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -X main.Version={{.Env.ARTIFACT_VERSION}}
archives:
  - name_template: "{{ .Binary }}"
    wrap_in_directory: false
    files:
      - LICENSE
checksum:
  algorithm: sha256
  split: true
changelog:
  disable: true
